# General Configuration Options
socket_path = "/run/container-management/container-management.sock" # Path to kanto-cm unix socket
stop_timeout = 5 # timeout (integer) in seconds before a SIGKILL is sent after a SIGTERM
log_tail_lines = 15

[keyconfig]
# Set button names and keyboard shortcuts
# Supports ctrl + key and alt+key combinations
# Example: string => key combination
# Example: ^q => ctrl + q
# Example: @q => alt + q
# Example: q => q
start_btn_name = "[S]tart"
start_kbd_key = "s"

stop_btn_name = "Sto[P]"
stop_kbd_key = "p"

remove_btn_name = "[R]emove"
remove_kbd_key = "r"

logs_btn_name = "[L]ogs"
logs_kbd_key = "l"

quit_btn_name = "^[Q]uit"
quit_kbd_key = "^q"

redeploy_btn_name = "^[D]eploy"
redeploy_kbd_key = "^d"

describe_btn_name = "[D]escribe"
describe_kbd_key = "d"

help_btn_name = "[H]elp"
help_kbd_key = "h"

# Includes a shell lexer so anything that would be a valid shell command can be used
# No pipes/redirects allowed.
# N.B.: Command inherits kantui's privileges (root)
# N.B.: For longer commands use sh -c <cmd>
redeploy_command = "systemctl restart kanto-auto-deployer.service"