[package]
name = "kanto-auto-deployer"
version = "0.1.0"
edition = "2021"
description = "Kanto Auto Deployer via a unix socket"
license = "Apache-2.0"
homepage = "https://github.com/eclipse-leda/leda-utils/tree/main/src/rust/kanto-auto-deployer"
repository = "https://github.com/eclipse-leda/leda-utils/tree/main/src/rust/kanto-auto-deployer"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11"
tokio = { version = "1.0", features = [ "rt-multi-thread", "time", "fs", "macros", "net",] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = {version = "0.8.2" }
tower = { version = "0.4" }
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = { version = "1.0.89", default-features = false, features = ["alloc"] }
glob = "0.3.0"

[build-dependencies]
tonic-build =  "0.8.2"

[[bin]]
name = "kanto-auto-deployer"
path = "src/main.rs"