# /********************************************************************************
# * Copyright (c) 2023 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * https://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

name: Leda-Utils Build

on:
  release:
    types: [published]

jobs:
  build-kantui:
    name: Build KantUI
    uses: ./.github/workflows/build-kantui.yml
    secrets: inherit

  build-kanto-auto-deployer:
    name: Build Kanto Auto Deployer
    uses: ./.github/workflows/build-kanto-auto-deployer.yml
    secrets: inherit

build-leda-utils:
    name: Build Leda-Utils
    uses: ./.github/workflows/build-leda-utils.yml
    secrets: inherit
