# /********************************************************************************
# * Copyright (c) 2023 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * https://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/
#

name: Build KantUI

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install Rust
        run: rustup update stable
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
      - name: Build binary
        run: |
          cd src/rust/kanto-tui
          cargo build --release
      - name: Package 
        run: |
          cp src/rust/kanto-tui/kantui_conf.toml . 
          cp src/rust/kanto-tui/target/${{ matrix.target }}/release/kantui . 
          chmod +x kantui
          tar czf kantui-${{ matrix.target }}.tar.gz kantui_conf.toml kantui
      - name: Upload files
        uses: actions/upload-artifact@v3
        with: 
          name: kantui-${{ matrix.target }}.tar.gz
          if-no-files-found: error
          path: kantui-${{ matrix.target }}.tar.gz
      - name: Debian Package Preparation
        run: |
          mkdir -p .debpkg/usr/bin
          mkdir -p .debpkg/etc/kantui
          cp kantui_conf.toml .debpkg/etc/kantui/
          cp kantui .debpkg/usr/bin
          chmod +x .debpkg/usr/bin/kantui
      - name: Set variables
        run: |
          echo "GIT_TAG=`echo $(git describe --tags --always)`" >> $GITHUB_ENV
          echo "package_version=`echo $(git describe --tags --always | tr -d [:alpha:])`" >> $GITHUB_ENV
          if [ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]; then
            echo "package_arch=arm64" >> $GITHUB_ENV
          elif if [ "${{ matrix.target }}" == "x86_64-unknown-linux-gnu" ];
            echo "package_arch=amd64" >> $GITHUB_ENV
          else
            echo "::error::Unknown architecture: ${{ matrix.target }}"
          fi
      - uses: jiro4989/build-deb-action@v2
        with:
          package: kantui
          package_root: .debpkg
          maintainer: Eclipse Leda Development Team
          version: '${{ env.package_version }}'
          arch: '${{ env.package_arch }}'
          depends: 'libc6 (>= 2.2.1), git'
          desc: 'User interface (ncurses) for Kanto Container Management'
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-deb
          path: |
            ./*.deb
